// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PagerApi.NetCore.Example.DB;

namespace PagerApi.NetCore.Example.Migrations
{
    [DbContext(typeof(TestContext))]
    [Migration("20181021042804_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("PagerApi.NetCore.Example.DB.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Texto");

                    b.HasKey("Id");

                    b.ToTable("Test");

                    b.HasData(
                        new { Id = 1, Texto = "Prueba1" },
                        new { Id = 2, Texto = "Prueba2" },
                        new { Id = 3, Texto = "Prueba3" },
                        new { Id = 4, Texto = "Prueba4" },
                        new { Id = 5, Texto = "Prueba5" },
                        new { Id = 6, Texto = "Prueba6" },
                        new { Id = 7, Texto = "Prueba7" },
                        new { Id = 8, Texto = "Prueba8" },
                        new { Id = 9, Texto = "Prueba9" },
                        new { Id = 10, Texto = "Prueba10" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
